services:
  - type: web
    name: eyes-disease-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.11.9
